# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupons',
            options={'verbose_name': 'Cupon', 'verbose_name_plural': 'Cupones'},
        ),
    ]
