# Generated by Django 3.1.7 on 2021-02-27 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210219_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders_detail',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
    ]
