# Generated by Django 3.1.6 on 2021-02-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre de la Categoria')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Tamaño')),
                ('price', models.FloatField(verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('img', models.ImageField(upload_to='', verbose_name='Imagen del Producto')),
                ('description', models.TextField(verbose_name='Descripcion del Producto')),
                ('heigth', models.FloatField(verbose_name='Altura del Producto (cm)')),
                ('width', models.FloatField(verbose_name='Ancho del Producto (cm)')),
                ('long', models.FloatField(verbose_name='Largo del Producto (cm)')),
                ('weigth', models.FloatField(verbose_name='Peso del Producto (kg)')),
                ('stock', models.IntegerField(verbose_name='Stock del Producto')),
                ('categoryId', models.ManyToManyField(related_name='products_as_category', to='products.Category')),
                ('sizeId', models.ManyToManyField(related_name='products_as_sizes', to='products.Size')),
            ],
        ),
    ]
