# Generated by Django 3.1.6 on 2021-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210219_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='products', verbose_name='Imagen del Producto'),
        ),
    ]
