# Generated by Django 3.1.6 on 2021-02-19 15:07

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210219_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoryId',
            field=models.ManyToManyField(related_name='categories', to='products.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to=products.models.path_and_rename, verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sizeId',
            field=models.ManyToManyField(related_name='sizes', to='products.Size'),
        ),
    ]
